drop table if exists tb_departamento cascade
drop table if exists tb_usuario cascade

create table tb_departamento (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
)

create table tb_usuario (
    id bigint generated by default as identity,
    id_departamento bigint,
    email varchar(255),
    name varchar(255),
    primary key (id)
)

alter table if exists tb_usuario
    add constraint FK6u6rubfuhxxndylvwkk5xoc0n
    foreign key (id_departamento)
    references tb_departamento